application: backend-project-1
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /js
  static_dir: js

- url: /static
  static_dir: static

- url: .*
  script: blog_fullstack.app

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico



libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
